services:
  appwrite-wellknown:
    image: appwrite-wellknown:0.1.0
    container_name: appwrite-wellknown
    build: .
    restart: always
    ports:
      - "8088:8080"
    environment:
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - APPWRITE_SELFSIGNED=${APPWRITE_SELFSIGNED}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_WELLKNOWN_FUNCTION_ID=${APPWRITE_WELLKNOWN_FUNCTION_ID}