name: wellknown_service
description: An new Dart Frog application
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_appwrite: ^10.0.0
  dart_frog: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
